# Site settings
title: "Quality Tactics / Qualit√§tstaktiken"
description: "Comprehensive handbook for software architects"
author: "Markus Harrer"
url: "https://qualitytactics.de"
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  tactics:
    output: true
    permalink: /:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "tactics"
    values:
      layout: "tactic"
  - scope:
      path: "de"
    values:
      lang: de
  - scope:
      path: "en"
    values:
      lang: en

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Sass
sass:
  style: compressed
  sass_dir: assets/css

# Languages
languages: ["de", "en"]
default_lang: "de"

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
  - vendor
